site_name: Powerfleet Automation Testing Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - Getting Started:
          - Web Testing:
                - Selenium (Windows): getting-started/web-testing/selenium.md
                - Playwright (Windows): getting-started/web-testing/playwright-windows.md
                - Playwright (Linux): getting-started/web-testing/playwright-linux.md
          - API Testing:
                - PyTest: getting-started/api-testing/pytest.md
                - Pester: getting-started/api-testing/pester.md
          - Mobile Testing:
                - Android: getting-started/mobile-testing/android.md
    - Writing Tests:
          - Selenium: writing-tests/selenium.md
          - Playwright: writing-tests/playwright.md
    - Debugging:
          - Introduction: debugging/debugging.md
          - Selenium: debugging/selenium.md
          - Playwright: debugging/playwright.md
    - Tutorials:
          - Web testing:
                - Tutorial 1: tutorials/web-testing/tutorial-1.md
                - Tutorial 2: tutorials/web-testing/tutorial-2.md
                - Tutorial 3: tutorials/web-testing/tutorial-3.md
                - Tutorial 4: tutorials/web-testing/tutorial-4.md
                - Tutorial 5: tutorials/web-testing/tutorial-5.md
                - Tutorial 6: tutorials/web-testing/tutorial-6.md
                - Tutorial 7: tutorials/web-testing/tutorial-7.md
                - Tutorial 8: tutorials/web-testing/tutorial-8.md
                - Tutorial 9: tutorials/web-testing/tutorial-9.md
                - Tutorial 10: tutorials/web-testing/tutorial-10.md
    - Advanced:
          - Linux Node setup: node-setup/linux-x64.md
    - Miscellaneous:
          - Environments: misc/environments.md
          - Azure: misc/azure.md
          - Git: misc/git.md

extra:
    author: Rofhiwa 'Ralph' Matumba
    version: 1.0

theme:
    name: material
    logo: static/logo.svg
    favicon: static/favicon.ico
    palette:
        - scheme: default
          primary: custom
          accent: custom
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - scheme: slate
          primary: custom
          accent: custom
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.sections
        - search.highlight
        - search.suggest
        - content.code.annotate
        - content.tabs.link
        - toc.integrate
        - navigation.top
        - navigation.instant
        - navigation.expand
        - header.autohide
        - palette.toggle
extra_css:
    - static/styles.css